{% set name = "metatrain" %}
{% set version = "2026.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatrain-{{ version }}.tar.gz
  sha256: a86e2eb8d63e4a3c667ff783eb68f1a1dce6b2f204820d4bc7fabbbb165508df

build:
  entry_points:
    - mtt = metatrain.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  ignore_run_exports:
    - pytorch *  # pytorch is only used as a Python package

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - huggingface_hub
    - python-metatensor-learn >=0.4.0,<0.5
    - python-metatensor-operations >=0.4.0,<0.5
    - python-metatensor-torch >=0.8.2,<0.9
    - python-metatomic-torch >=0.1.6,<0.2
    - jsonschema
    - pydantic >=2.12
    - omegaconf >=2.3.0
    - python-hostlist
    - pytorch
    - python-vesin

test:
  imports:
    - metatrain
  commands:
    - pip check
    - mtt --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/metatensor/metatrain
  summary: Training and evaluating machine learning models for atomistic systems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://metatensor.github.io/metatrain

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
