{% set name = "metatrain" %}
{% set version = "2025.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatrain-{{ version }}.tar.gz
  sha256: 7eeb75f0e155854405d091c9691094e8e995387d2603556200785f0da13bb650

build:
  entry_points:
    - mtt = metatrain.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ase <3.23.0
    - metatensor-learn ==0.3.1
    - metatensor-operations ==0.3.1
    - metatensor-torch ==0.7.2
    - jsonschema
    - omegaconf
    - python-hostlist
    - pytorch
    - vesin
    - numpy <2.0.0

test:
  imports:
    - metatrain
  commands:
    - pip check
    - mtt --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://metatensor.github.io/metatrain
  summary: Training and evaluating machine learning models for atomistic systems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://metatensor.github.io/metatrain

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
